# Site settings
title: EE 227C (Spring 2018) Convex Optimization and Approximation
email: 
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yz14.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
